trigger:
  branches:
    include:
      - main

pool:
  name: "Default"
  demands:
    - agent.name -equals BO7A

steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
      pip install pre-commit
    displayName: "Install Pre-commit"

  - script: |
      pre-commit install
    displayName: "Install Pre-commit Hooks"

  - script: |
      pre-commit run --all-files
    displayName: "Run Pre-commit Hooks"

  - script: |
      echo "Pre-commit hooks completed."
    displayName: "Final Step"
